platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true

target 'KFXLogUI_Example' do
  pod 'KFXLogUI', :path => '../'

	### If using from trunk
	source 'https://cdn.cocoapods.org/'
  pod 'KFXLog'

  target 'KFXLogUI_Tests' do
    inherit! :search_paths

    
  end
end
