use_frameworks!

platform :ios, '8.2'

target 'KFXLogUI_Example' do
  pod 'KFXLogUI', :path => '../'
	
  pod 'KFXLog', :git => 'https://github.com/ChristianFox/KFXLog.git', :branch => 'feature/moveUIIntoNewPod'

  target 'KFXLogUI_Tests' do
    inherit! :search_paths

    
  end
end
